name: platterwave
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  maps_launcher: ^2.2.0
  flutter_svg:
  provider: ^6.0.3
  cached_network_image:
  the_validator: ^2.0.0
  get_it: ^7.2.0
  svg_icon:
  intl_phone_field: ^3.1.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  overlay_support: ^2.0.1
  jiffy: ^5.0.0
  firebase_storage: ^11.0.10
  image_picker: ^0.8.7+5
  readmore: ^2.2.0
  shimmer: ^2.0.0
  like_button: ^2.0.5
  hive: ^2.2.3
  share_plus:
  video_player: ^2.6.1
  linkfy_text: ^1.1.5
  url_launcher: ^6.1.7
  sign_in_with_apple: ^4.2.0
  flutter_login_facebook: ^1.6.2
  google_sign_in:
  firebase_dynamic_links: ^5.0.11
  firebase_messaging:
  get_time_ago: ^1.1.7
  flutter_local_notifications: ^12.0.4
  bot_toast: ^4.0.3
  sticky_headers: ^0.3.0+2
  video_thumbnail: ^0.5.3
  gallery_image_viewer: ^1.2.0
  chewie: ^1.5.0
  im_animations: ^0.1.2
  smooth_page_indicator: ^1.0.0+2
  sliding_up_panel: ^2.0.0+1
  flutter_rating_bar: ^4.0.1
  omni_datetime_picker:
  barcode_widget: ^2.0.3
  currency_formatter: ^1.2.0
  liquid_pull_to_refresh: ^3.0.1
  carousel_slider: ^4.2.1
  location_picker_flutter_map:
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  flutter_paystack_payment_plus:
  http:
  number_inc_dec: ^0.8.0
  awesome_place_search: ^1.0.7
  flutter_parsed_text_field: ^0.1.10
  custom_text: ^1.0.0
  path_provider: ^2.0.15
  flutter_google_places_hoc081098: ^1.2.0
  google_maps_webservice_ex: ^0.0.1+2
  date_time_picker: ^2.1.0
  photo_view: ^0.14.0
  pay_with_paystack: 1.0.2
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/appicon2.png"
  remove_alpha_ios: true
  min_sdk_android: 21

dev_dependencies:
  flutter_native_splash:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icon/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/font/Satoshi-Bold.otf
          weight: 900
        - asset: assets/font/Satoshi-Bold.otf
          weight: 900
        - asset: assets/font/Satoshi-Bold.otf
          weight: 700
        - asset: assets/font/Satoshi-Regular.otf
          weight: 400
        - asset: assets/font/Satoshi-Medium.otf
          weight: 600
        - asset: assets/font/Satoshi-Bold.otf
          weight: 800