// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLNHyvPmLhsrk6M8Oy9U-38iQfiLD7foo',
    appId: '1:487663652425:android:b0916125994471a1f2b998',
    messagingSenderId: '487663652425',
    projectId: 'platterwise',
    databaseURL: 'https://platterwise-default-rtdb.firebaseio.com',
    storageBucket: 'platterwise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJEwxdBa0p-FJgB8Ltu9Mh2rr-KXtG55Y',
    appId: '1:487663652425:ios:d5d3b82611e349f0f2b998',
    messagingSenderId: '487663652425',
    projectId: 'platterwise',
    databaseURL: 'https://platterwise-default-rtdb.firebaseio.com',
    storageBucket: 'platterwise.appspot.com',
    androidClientId: '487663652425-35rg14lqsjt06u04hrcsef3senojb04r.apps.googleusercontent.com',
    iosClientId: '487663652425-6812n6jqahq60buvh6o9qgd50hfutlfm.apps.googleusercontent.com',
    iosBundleId: 'com.platterwave.net',
  );
}
